In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [2]:
df=pd.read_csv("bangalore house price prediction OHE-data.csv")
df.head()

bath  balcony  price  total_sqft_int  bhk  price_per_sqft  \
0   3.0      2.0  150.0          1672.0    3     8971.291866   
1   3.0      3.0  149.0          1750.0    3     8514.285714   
2   3.0      2.0  150.0          1750.0    3     8571.428571   
3   2.0      2.0   40.0          1250.0    2     3200.000000   
4   2.0      2.0   83.0          1200.0    2     6916.666667   

   area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                              1                        0   
1                              0                        1   
2                              1                        0   
3                              1                        0   
4                              0                        0   

   area_typePlot  Area  availability_Ready To Move  ...  \
0                    0                           1  ...   
1                    0                           1  ...   
2                    0                           1  ...   
3                    0                           1  ...   
4                    1                           1  ...   

   location_Kalena Agrahara  location_Horamavu Agara  location_Vidyaranyapura  \
0                         0                        0                        0   
1                         0                        0                        0   
2                         0                        0                        0   
3                         0                        0                        0   
4                         0                        0                        0   

   location_BTM 2nd Stage  location_Hebbal Kempapura  location_Hosur Road  \
0                       0                          0                    0   
1                       0                          0                    0   
2                       0                          0                    0   
3                       0                          0                    0   
4                       0                          0                    0   

   location_Horamavu Banaswadi  location_Domlur  location_Mahadevpura  \
0                            0                0                     0   
1                            0                0                     0   
2                            0                0                     0   
3                            0                0                     0   
4                            0                0                     0   

   location_Tumkur Road  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  

[5 rows x 108 columns]

In [3]:
house=pd.read_csv("Bengaluru_House_Data.csv") 
house.head()
# The data contain object and string and other we needs to convert into numeric that the model is easily train


area_type   availability                  location       size  \
0  Super built-up  Area         19-Dec  Electronic City Phase II      2 BHK   
1            Plot  Area  Ready To Move          Chikka Tirupathi  4 Bedroom   
2        Built-up  Area  Ready To Move               Uttarahalli      3 BHK   
3  Super built-up  Area  Ready To Move        Lingadheeranahalli      3 BHK   
4  Super built-up  Area  Ready To Move                  Kothanur      2 BHK   

   society total_sqft  bath  balcony   price  
0  Coomee        1056   2.0      1.0   39.07  
1  Theanmp       2600   5.0      3.0  120.00  
2      NaN       1440   2.0      3.0   62.00  
3  Soiewre       1521   3.0      1.0   95.00  
4      NaN       1200   2.0      1.0   51.00

One-hot encoding is a technique used to convert categorical data into a numerical format so that it can be used by machine learning algorithms. Many algorithms require input data to be in numerical form, and one-hot encoding is commonly used for this purpose.

### How One-Hot Encoding Works:
- **Categorical Variables**: These are variables that contain labels or categories (e.g., "Red," "Green," "Blue").
- **Convert to Binary Vectors**: One-hot encoding transforms each category into a binary vector (a vector containing only 0s and 1s).
  
For example, if you have a categorical variable like "Color" with three possible values: `Red`, `Green`, and `Blue`, one-hot encoding would represent it as:

| Color  | One-Hot Encoding |
|--------|------------------|
| Red    | [1, 0, 0]        |
| Green  | [0, 1, 0]        |
| Blue   | [0, 0, 1]        |

### Why One-Hot Encoding is Useful:
- **Avoids Ordinal Relationships**: If you simply assign integers (e.g., Red = 1, Green = 2, Blue = 3), the algorithm might interpret this as implying an order or relationship between the categories. One-hot encoding prevents this by treating each category independently.
- **Supports Machine Learning Algorithms**: Many algorithms (like neural networks and tree-based models) require numeric input, so one-hot encoding is a way to transform categorical variables without introducing bias or incorrect assumptions.

One-hot encoding is typically implemented using libraries like `pandas` or `scikit-learn` in Python:

```python
import pandas as pd

# Example DataFrame
df = pd.DataFrame({'Color': ['Red', 'Green', 'Blue']})

# Apply One-Hot Encoding
df_encoded = pd.get_dummies(df, columns=['Color'])
print(df_encoded)
```

This would output:

```
   Color_Blue  Color_Green  Color_Red
0           0            0          1
1           0            1          0
2           1            0          0
```

In [4]:
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
ohe=OneHotEncoder()
ohe.fit_transform(house).toarray()[0].shape

(8248,)

In [5]:
house.location.value_counts()

Whitefield                        540
Sarjapur  Road                    399
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ... 
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Abshot Layout                       1
Name: location, Length: 1305, dtype: int64

In [6]:
pd.get_dummies(house.area_type)

Built-up  Area  Carpet  Area  Plot  Area  Super built-up  Area
0                   0             0           0                     1
1                   0             0           1                     0
2                   1             0           0                     0
3                   0             0           0                     1
4                   0             0           0                     1
...               ...           ...         ...                   ...
13315               1             0           0                     0
13316               0             0           0                     1
13317               1             0           0                     0
13318               0             0           0                     1
13319               0             0           0                     1

[13320 rows x 4 columns]

In [7]:
df.shape

(7120, 108)

# splite data

In [9]:
X=df.drop("price",axis=1)
y=df["price"]

print("shape of x",X.shape)
print("shape of y",y.shape)

shape of x (7120, 107)
shape of y (7120,)


In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

print("shape of x_train",X_train.shape)
print("shape of y_train",y_train.shape)
print("shape of X_test",X_test.shape)
print("shape of y_test",y_test.shape)

shape of x_train (5696, 107)
shape of y_train (5696,)
shape of X_test (1424, 107)
shape of y_test (1424,)


# Polynomial linear  Regression ML model Training

In [14]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [16]:
poly_reg=PolynomialFeatures()
poly_reg.fit(X_train)
X_train_poly=poly_reg.transform(X_train)
X_test_poly=poly_reg.transform(X_test)

In [18]:
X_train_poly.shape,X_test_poly

((5696, 5886),
 array([[1., 2., 2., ..., 0., 0., 0.],
        [1., 2., 2., ..., 0., 0., 0.],
        [1., 2., 1., ..., 0., 0., 0.],
        ...,
        [1., 2., 2., ..., 0., 0., 0.],
        [1., 2., 1., ..., 0., 0., 0.],
        [1., 2., 1., ..., 0., 0., 0.]]))

In [19]:
lr=LinearRegression()
lr.fit(X_train_poly,y_train)

LinearRegression()

In [20]:
lr.score(X_train_poly,y_train)

1.0

In [21]:
lr.score(X_test_poly,y_test)

1.0

In [22]:
lr.predict([X_test_poly[0,:]])

array([47.])

In [23]:
y_pred=lr.predict(X_test_poly)
y_pred

array([47. , 60. , 65. , ..., 56.5, 26. , 49. ])

In [24]:
pd.DataFrame({"orignal":y_test,"predicted":y_pred})

orignal  predicted
960      47.0       47.0
132      60.0       60.0
2431     65.0       65.0
2229    325.0      325.0
4503     60.0       60.0
...       ...        ...
4970     48.0       48.0
553     205.0      205.0
1397     56.5       56.5
4056     26.0       26.0
1817     49.0       49.0

[1424 rows x 2 columns]

In [25]:
from sklearn.metrics import mean_squared_error
mse=mean_squared_error(y_test,y_pred)
rmse=np.sqrt(mse)

mse,rmse


(9.516041508729012e-26, 3.0848081802162373e-13)

# Simple Linear Regression on same Data

In [26]:
lr.fit(X_train,y_train)

LinearRegression()

In [27]:
lr.score(X_train,y_train)

0.8439925248308795

In [28]:
lr.score(X_test,y_test)

0.9196808132211663